version: "3.6"
services:
  service-discovery:
    image: servicediscovery:2.0
    build: ./servicediscovery
    ports:
      - 8761:8761
    restart: on-failure
    networks:
      - gipher-api-network

  api-gateway-service:
    image: apigatewayimg
    build: ./api-gateway-service
    ports:
      - 8765:8765
    environment:
      EUREKA_HOST: service-discovery
    depends_on:
      - service-discovery
    restart: on-failure
    networks:
      - gipher-api-network

  gipher-spring:
    image: gipher-spring:2.0
    build: ./gipher-spring
    ports:
      - 8000:8000
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      EUREKA_HOST: service-discovery
    depends_on:
      - mysqldb
      - service-discovery
      - api-gateway-service
    restart: on-failure
    networks:
      - gipher-api-network

  mysqldb:
    image: mysql:8.0.24
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_register
    networks:
      - gipher-api-network

  gipher-manager:
    image: giphermanager:2.0
    build: ./giphermanager
    ports:
      - 9090:9090
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      EUREKA_HOST: service-discovery
    depends_on:
      - mongodb
      - service-discovery
      - api-gateway-service
    restart: on-failure
    networks:
      - gipher-api-network

  mongodb:
    image: mongo:4.0.25
    ports:
      - 27017:27017

    networks:
      - gipher-api-network

networks:
  gipher-api-network:
