server:
  port: 8765

spring:
  application:
    name: api-gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: user_route
#          url: "lb://user-service"
#          predicates:
#            - Path=/api/v1/user/**
#        - id: gipher_route
#          url: "lb://gipher-service"
#          predicates:
#            - Path=/api/v1/gipher/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/